# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78ffcdc200defc9ae747203262713c71067e194ae986e07783cc3223b747f502a82feb2cd9b73851ef9043eab7f5f083f7a4b713d21936dbe736d77868602199

test:
  secret_key_base: c5aaabd8a7f2bc091e455c0e57f6bbd869afd580ba68afa14122c62e7f708e55211f8b86683e92f273bb828c1ce41d1dfeb12faf6ed5bb0bc7940e08e8c1741f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
